rails_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { registrations: 'registrations' }
  
  resources :articles do 
    resources :comments
  end
  
  get root to: 'pages#index'
  get 'pages/contact'
  get 'pages/about'
  
end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

rails_app/app/models/article.rb
class Article < ApplicationRecord
  
  validates :title
  validates :body
  
  belongs_to :user
  has_many :comments
  
end

rails_app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

rails_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :articles
  has_many :comments
  
end

rails_app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

rails_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
     
     
  def  create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user_id = current_user.id if current_user
    

      if @comment.save
        redirect_to article_path(@article), notice: 'Your comment has been saved!'
      else 
        redirect_to 'new'
      end
  end
  
  def  update
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    

    
      if @comment.update(comment_params)
        redirect_to article_path(@article), notice: 'Your comment has been updated!'
      else 
        render 'edit'
      end
  end
  
  def  edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end
  
  def  delete
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    
    @comment.destroy
    redirect_to article_path(@article), notice: 'Your comment has been deleted!'
  end

    private
      def comment_params
        params.require(:comment).permit(:body)
      end

end

rails_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @article = Article.last(4)
  end
end

rails_app/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  #route za index page nakon Sign upa
  def after_sign_up_path_for(resource)
     root_path 
  end
  
 private
 
 def sign_up_params
 params.require(:user).permit(
 :email,
 :password,
 :password_confirmation,
 :username,
 :firstname,
 :lastname
 )
 end
 
 def account_update_params
 params.require(:user).permit(
 :email,
 :password,
 :password_confirmation,
 :current_password,
 :username,
 :firstname,
 :lastname
 )
 end
end

rails_app/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails_app/app/helpers/pages_helper.rb
module PagesHelper
end

rails_app/app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">

  <p>
    <strong>Created by: </strong>
    <%= article.user.username %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

rails_app/app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

rails_app/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

rails_app/app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

rails_app/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

rails_app/app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>
<%= render @article.comments %><br>
<%= render 'comments/form' %><br>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "All articles", articles_path %> |
  <%= link_to "Home page", root_path %>
  
  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

rails_app/app/views/comments/_comment.html.erb
<div class="media">
 <div class="pull-left">
  
    <%= comment.user.username %>
  
 </div>
 <div class="media-body"><br>
 
      <%= comment.body %>
 
   <p class="media-heading pull-right">
     
      <%= time_ago_in_words(comment.created_at) %>
     
   </p><br>

 </div>
</div>

<%= link_to "Edit", edit_article_comment_path(comment.article, comment) %>

<%= link_to "Delete", [comment.article, comment], method: :delete, data: {confirm: "Are you sure?" } %>

rails_app/app/views/comments/_form.html.erb
<%= simple_form_for ([@article, @article.comments.build]) do |f| %>

<%= f.input :body %>
<%= f.submit "Post your comment!" %>

<% end %>

rails_app/app/views/comments/edit.html.erb
<h1> Edit Comment</h1>

<%= simple_form_for([@article, @comment]) do |f| %>

  <%= f.input :body %>
  <%= f.submit %>

<% end %>

rails_app/app/views/layouts/_footer.html.erb
<!-- prvi footer -->
<footer class="footer-distributed">
<div class="footer-right">
<div class="footer-icons">
<a href="#"><i class="fa">
    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="50" height="50"viewBox="0 0 50 50"fill="#fff"><path d="M 16 3 C 8.8324839 3 3 8.8324839 3 16 L 3 34 C 3 41.167516 8.8324839 47 16 47 L 34 47 C 41.167516 47 47 41.167516 47 34 L 47 16 C 47 8.8324839 41.167516 3 34 3 L 16 3 z M 16 5 L 34 5 C 40.086484 5 45 9.9135161 45 16 L 45 34 C 45 40.086484 40.086484 45 34 45 L 16 45 C 9.9135161 45 5 40.086484 5 34 L 5 16 C 5 9.9135161 9.9135161 5 16 5 z M 37 11 A 2 2 0 0 0 35 13 A 2 2 0 0 0 37 15 A 2 2 0 0 0 39 13 A 2 2 0 0 0 37 11 z M 25 14 C 18.936712 14 14 18.936712 14 25 C 14 31.063288 18.936712 36 25 36 C 31.063288 36 36 31.063288 36 25 C 36 18.936712 31.063288 14 25 14 z M 25 16 C 29.982407 16 34 20.017593 34 25 C 34 29.982407 29.982407 34 25 34 C 20.017593 34 16 29.982407 16 25 C 16 20.017593 20.017593 16 25 16 z"></path></svg>
</i></a>
<a href="#"><i class="fa">
    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"width="50" height="50"viewBox="0 0 50 50"fill="#fff"><path d="M 25 3 C 12.861562 3 3 12.861562 3 25 C 3 36.019135 11.127533 45.138355 21.712891 46.728516 L 22.861328 46.902344 L 22.861328 29.566406 L 17.664062 29.566406 L 17.664062 26.046875 L 22.861328 26.046875 L 22.861328 21.373047 C 22.861328 18.494965 23.551973 16.599417 24.695312 15.410156 C 25.838652 14.220896 27.528004 13.621094 29.878906 13.621094 C 31.758714 13.621094 32.490022 13.734993 33.185547 13.820312 L 33.185547 16.701172 L 30.738281 16.701172 C 29.349697 16.701172 28.210449 17.475903 27.619141 18.507812 C 27.027832 19.539724 26.84375 20.771816 26.84375 22.027344 L 26.84375 26.044922 L 32.966797 26.044922 L 32.421875 29.564453 L 26.84375 29.564453 L 26.84375 46.929688 L 27.978516 46.775391 C 38.71434 45.319366 47 36.126845 47 25 C 47 12.861562 37.138438 3 25 3 z M 25 5 C 36.057562 5 45 13.942438 45 25 C 45 34.729791 38.035799 42.731796 28.84375 44.533203 L 28.84375 31.564453 L 34.136719 31.564453 L 35.298828 24.044922 L 28.84375 24.044922 L 28.84375 22.027344 C 28.84375 20.989871 29.033574 20.060293 29.353516 19.501953 C 29.673457 18.943614 29.981865 18.701172 30.738281 18.701172 L 35.185547 18.701172 L 35.185547 12.009766 L 34.318359 11.892578 C 33.718567 11.811418 32.349197 11.621094 29.878906 11.621094 C 27.175808 11.621094 24.855567 12.357448 23.253906 14.023438 C 21.652246 15.689426 20.861328 18.170128 20.861328 21.373047 L 20.861328 24.046875 L 15.664062 24.046875 L 15.664062 31.566406 L 20.861328 31.566406 L 20.861328 44.470703 C 11.816995 42.554813 5 34.624447 5 25 C 5 13.942438 13.942438 5 25 5 z"></path></svg>
</i></a>
<a href="#"><i class="fa">
    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"width="50" height="50"viewBox="0 0 50 50"fill="#fff"><path d="M 24.402344 9 C 17.800781 9 11.601563 9.5 8.300781 10.199219 C 6.101563 10.699219 4.199219 12.199219 3.800781 14.5 C 3.402344 16.898438 3 20.5 3 25 C 3 29.5 3.398438 33 3.898438 35.5 C 4.300781 37.699219 6.199219 39.300781 8.398438 39.800781 C 11.902344 40.5 17.898438 41 24.5 41 C 31.101563 41 37.097656 40.5 40.597656 39.800781 C 42.800781 39.300781 44.699219 37.800781 45.097656 35.5 C 45.5 33 46 29.402344 46.097656 24.902344 C 46.097656 20.402344 45.597656 16.800781 45.097656 14.300781 C 44.699219 12.101563 42.800781 10.5 40.597656 10 C 37.097656 9.5 31 9 24.402344 9 Z M 24.402344 11 C 31.601563 11 37.398438 11.597656 40.199219 12.097656 C 41.699219 12.5 42.898438 13.5 43.097656 14.800781 C 43.699219 18 44.097656 21.402344 44.097656 24.902344 C 44 29.199219 43.5 32.699219 43.097656 35.199219 C 42.800781 37.097656 40.800781 37.699219 40.199219 37.902344 C 36.597656 38.601563 30.597656 39.097656 24.597656 39.097656 C 18.597656 39.097656 12.5 38.699219 9 37.902344 C 7.5 37.5 6.300781 36.5 6.101563 35.199219 C 5.300781 32.398438 5 28.699219 5 25 C 5 20.398438 5.402344 17 5.800781 14.902344 C 6.101563 13 8.199219 12.398438 8.699219 12.199219 C 12 11.5 18.101563 11 24.402344 11 Z M 19 17 L 19 33 L 33 25 Z M 21 20.402344 L 29 25 L 21 29.597656 Z"></path></svg>
</i></a>
<a href="#"><i class="fa">
    <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px"width="48" height="48"viewBox="0 0 24 24"style=" fill:#fff;">    <path d="M10.9,2.1c-4.6,0.5-8.3,4.2-8.8,8.7c-0.6,5,2.5,9.3,6.9,10.7v-2.3c0,0-0.4,0.1-0.9,0.1c-1.4,0-2-1.2-2.1-1.9 c-0.1-0.4-0.3-0.7-0.6-1C5.1,16.3,5,16.3,5,16.2C5,16,5.3,16,5.4,16c0.6,0,1.1,0.7,1.3,1c0.5,0.8,1.1,1,1.4,1c0.4,0,0.7-0.1,0.9-0.2 c0.1-0.7,0.4-1.4,1-1.8c-2.3-0.5-4-1.8-4-4c0-1.1,0.5-2.2,1.2-3C7.1,8.8,7,8.3,7,7.6C7,7.2,7,6.6,7.3,6c0,0,1.4,0,2.8,1.3 C10.6,7.1,11.3,7,12,7s1.4,0.1,2,0.3C15.3,6,16.8,6,16.8,6C17,6.6,17,7.2,17,7.6c0,0.8-0.1,1.2-0.2,1.4c0.7,0.8,1.2,1.8,1.2,3 c0,2.2-1.7,3.5-4,4c0.6,0.5,1,1.4,1,2.3v3.3c4.1-1.3,7-5.1,7-9.5C22,6.1,16.9,1.4,10.9,2.1z"></path></svg>
</i></a>
</div>
</div>
<div class="footer-left">
<p class="footer-links">
·
<%= link_to "Contact Us", pages_contact_path%>
·
<%= link_to "About Us", pages_contact_path%>
·
</p>
<p> </p>
</div>
</footer>

rails_app/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Aplikacija", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "About Us", pages_about_path %></li>
        <li><%= link_to "Contact Us", pages_contact_path %></li>
        <li><%= link_to "Create new article", new_article_path %></li>
        
        <% if !current_user %>
        
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        
        <% else %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Edit my profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path %></li>
          </ul>
        </li>
        
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rail aplilkacija</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= bootstrap_flash %>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
  </body>
</html>

rails_app/app/views/pages/_mailer.html.erb
<div class="row">
 <div class="col-md-4 col-md-offset-4">
 <div class="well">
 <%= simple_form_for @c do |f| %>
 <%= f.input :name %>
 <%= f.input :email %>
 <%= f.input :message %>
 <%= f.submit "Get in touch!", class: "btn btn-info" %>
 <% end %>
 </div>
 </div>
</div>

rails_app/app/views/pages/about.html.erb
<div class="row">
 <div class="col-lg-12 text-center">
 <h1>About Us</h1>
 <p class="lead">Test Text</p>
 <ul class="list-unstyled">
 <li>List Item</li>
 <li>List Item 2</li>
 </ul>
 </div>
</div>

rails_app/app/views/pages/contact.html.erb
<div class="row">
 <div class="col-lg-12 text-center">
  <h1>Contact Us</h1>
  <p class="lead">Test Text</p>
  <ul class="list-unstyled">
    <li>List Item</li>
    <li>List Item 2</li>
  </ul>
  <form action="" method="post" class="input-group">
    <div class="input-group">
        <label for="mail">E-mail</label>
        <input type="email" name="mail" class="form-control">
    </div>
    <div class="input-group">
        <label for="naziv">Naziv</label>
        <input type="text" name="naziv"class="form-control">
    </div>
    <div class="input-group">
        <label for="razlog">Razlog</label>
        <input type="text" name="razlog"class="form-control">
    </div>
    <div class="input-group">
        <div class="input upit-wrapper">
            <label for="upit">Upit/poruka</label>
            <textarea name="upit"class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-default" data-aos="zoom-out">Pošalji</button>
    </div>
  </form>
 </div>
</div>

rails_app/app/views/pages/index.html.erb
<div class="row">
  <!-- Blog Post Content Column -->
  <div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <h1>Blog Post Title</h1>
    <!-- Author -->
    <p class="lead">
    by <a href="#">Start Bootstrap</a>
    </p>
    <hr>
    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
    <hr>
    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
    <hr>
    <!-- Post Content -->
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
   obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi
   eos magni recusandae laborum minus inventore?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum
   quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat.
   Temporibus, voluptatibus.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto
   blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat
   perspiciatis. Enim, iure!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas
   placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem
   obcaecati?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo,
   aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam
   recusandae? Qui, necessitatibus, est!</p>
    <hr>
    <!-- Blog Comments -->
    <!-- Comments Form -->
    <div class="well">
     <h4>Leave a Comment:</h4>
     <form role="form">
      <div class="form-group">
      <textarea class="form-control" rows="3"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
     </form>
    </div>
    <hr>
    <!-- Posted Comments -->
    <!-- Comment -->
    <div class="media">
     <a class="pull-left" href="#">
     <img class="media-object" src="http://placehold.it/64x64" alt="">
     </a>
     <div class="media-body">
      <h4 class="media-heading">Start Bootstrap<small>August 25, 2014 at 9:30 PM</small></h4>
      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
      commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
      ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
      </div>
    </div>
   <!-- Comment -->
   <div class="media">
    <a class="pull-left" href="#">
    <img class="media-object" src="http://placehold.it/64x64" alt="">
    </a>
    <div class="media-body">
     <h4 class="media-heading">Start Bootstrap
     <small>August 25, 2014 at 9:30 PM</small>
     </h4>
     Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
    commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
    ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
     <!-- Nested Comment -->
     <div class="media">
      <a class="pull-left" href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="">
      </a>
      <div class="media-body">
       <h4 class="media-heading">Nested Start Bootstrap<small>August 25, 2014 at 9:30 PM</small></h4>
       Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
      commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
      ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
       </div>
      </div>
      <!-- End Nested Comment -->
     </div>
    </div>
   </div>
   <!-- Blog Sidebar Widgets Column -->
   <div class="col-md-4">
   <!-- Blog Search Well -->
   <div class="well">
    <h4>Blog Search</h4>
    <div class="input-group">
     <input type="text" class="form-control">
     <span class="input-group-btn">
      <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span> </button>
     </span>
    </div>
    <!-- /.input-group -->
   </div>
   <!-- Blog Categories Well -->
   <div class="well">
    <h4>Blog Categories</h4>
    <div class="row">
     <div class="col-lg-6">
      <ul class="list-unstyled">
       <li><a href="#">Category Name</a></li>
       <li><a href="#">Category Name</a></li>
       <li><a href="#">Category Name</a></li>
       <li><a href="#">Category Name</a></li>
      </ul>
     </div>
     <div class="col-lg-6">
      <ul class="list-unstyled">
       <li><a href="#">Category Name</a></li>
       <li><a href="#">Category Name</a></li>
       <li><a href="#">Category Name</a></li>
       <li><a href="#">Category Name</a></li>
      </ul>
     </div>
    </div>
    <!-- /.row -->
   </div>
   <!-- Side Widget Well -->
   <div class="well">
     
    <h4>Recent posts</h4>
    <% @article.each do |article| %>
    
     <strong><%= link_to article.title, article %></strong><br>
     <br>
     Created by: <%= article.user.username %><br>
     <p><%= truncate(article.body) %></p><br>
    
    <% end %>
     
   </div>
  </div>
</div>
<!-- /.row -->
<hr>